---
- name: upgrade
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: python3
  tasks:
    - name: set timezone
      community.general.timezone:
        name: Europe/Paris
    - name: upgrade
      apt:
        upgrade: true
        update_cache: true
    - name: stat reboot-required file
      stat:
        path: /var/run/reboot-required
      register: _reboot_required_stat
    - name: debug _reboot_required_stat
      debug:
        var: _reboot_required_stat
    - name: reboot if required
      reboot:
      when: _reboot_required_stat.stat.exists
- name: install yunohost
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: python3
    installation_script_path: /tmp/yunohost_installation_script.sh
  tasks:
    - name: stat /etc/yunohost directory
      stat:
        path: /etc/yunohost
      register: _stat_etc_yunohost
    - block:
        - name: retrieve ynh installation script
          get_url:
            url: https://install.yunohost.org
            dest: "{{ installation_script_path }}"
            mode: +x
            owner: root
            group: root
        - name: install yunohost
          command: bash {{ installation_script_path }} -a -f
          # -a automatic and -f do not run checks
        # I don't know why, after YNH installation, dnsmasq is down...
        # dnsmasq.service: Start-post operation timed out. Stopping.
        # found a post on YNH forum with no answer:
        # https://forum.yunohost.org/t/dnsmasq-fails-to-start-in-post-install-on-fresh-system/10153
        # so I just use a workaround, start the service...
        - name: ensure dnsmasq service is started
          service:
            name: dnsmasq
            state: started
        - name: install python3-pip
          apt:
            name: python3-pip
        - name: install pexpect
          pip:
            executable: pip3
            name: pexpect
        - name: run post installation
          ansible.builtin.expect:
            command: yunohost tools postinstall
            timeout: null
            responses:
              (?i)main domain: restic.test
              (?i)administration password: This is my password!
        - name: remove installation script
          file:
            path: "{{ installation_script_path }}"
            state: absent
      when: not _stat_etc_yunohost.stat.exists

- name: install restic
  hosts: all
  become: true
  vars:
    restic_username: resticbackup
  tasks:
    - name: add backup user
      user:
        name: "{{ restic_username }}"
    - name: install restic
      command: >-
        yunohost app install --force /restic_ynh -a "server=localhost&ssh_user=resticbackup&passphrase=APassphrase&conf=1&port=22&backup_path=&data=1&app=all&allow_extra_space_use=1&on_calendar=Daily&check_on_calendar=*-*-8,15,22&check_read_data_on_calendar=*-*-1&domain=sub.domain.tld&path=&admin=package_checker&is_public=&apps=all"
      args:
        creates: /opt/yunohost/restic
    - name: get ssh key
      command: cat /root/.ssh/id_restic_ed25519.pub
      changed_when: false
      register: _restic_public_key
    - name: ensure .ssh directory exists for user {{ restic_username }}
      file:
        path: /home/{{ restic_username }}/.ssh
        mode: u=rwx,go=
        state: directory
        owner: "{{ restic_username }}"
        group: "{{ restic_username }}"
    - name: ensure restic public key is authorized on user {{ restic_username }}
      lineinfile:
        create: true
        mode: u=rw,go=
        owner: "{{ restic_username }}"
        group: "{{ restic_username }}"
        path: /home/{{ restic_username }}/.ssh/authorized_keys
        line: "{{ _restic_public_key.stdout }}"
- name: check that a backup works
  hosts: all
  become: true
  vars:
    restic_username: resticbackup
    restic_password: APassphrase
  tasks:
    - name: start a backup
      service:
        name: restic
        state: started
    - name: list snapshots on restic backup repository
      environment:
        RESTIC_PASSWORD: "{{ restic_password }}"
      command: restic -r /home/{{ restic_username }}/auto_restic list snapshots
      changed_when: false
      register: _restic_snapshots
    - name: Ensure repository contains snapshots
      assert:
        that: _restic_snapshots.stdout | length > 0
        fail_msg: No snapshot was found in auto_restic repository
        success_msg: Found at least 1 snapshot in repository
