---
- name: upgrade
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: python3
  tasks:
    - name: set timezone
      community.general.timezone:
        name: Europe/Paris
    - name: upgrade
      apt:
        upgrade: true
        update_cache: true
    - name: stat reboot-required file
      stat:
        path: /var/run/reboot-required
      register: _reboot_required_stat
    - name: debug _reboot_required_stat
      debug:
        var: _reboot_required_stat
    - name: reboot if required
      reboot:
      when: _reboot_required_stat.stat.exists
- name: install yunohost
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: python3
    installation_script_path: /tmp/yunohost_installation_script.sh
  tasks:
    - name: stat /etc/yunohost directory
      stat:
        path: /etc/yunohost
      register: _stat_etc_yunohost
    - block:
        - name: retrieve ynh installation script
          get_url:
            url: https://install.yunohost.org
            dest: "{{ installation_script_path }}"
            mode: +x
            owner: root
            group: root
        - name: install yunohost
          command: bash {{ installation_script_path }} -a -f
          # -a automatic and -f do not run checks
        # I don't know why, after YNH installation, dnsmasq is down...
        # dnsmasq.service: Start-post operation timed out. Stopping.
        # found a post on YNH forum with no answer:
        # https://forum.yunohost.org/t/dnsmasq-fails-to-start-in-post-install-on-fresh-system/10153
        # so I just use a workaround, start the service...
        - name: ensure dnsmasq service is started
          service:
            name: dnsmasq
            state: started
        - name: install python3-pip
          apt:
            name: python3-pip
        - name: install pexpect
          pip:
            executable: pip3
            name: pexpect
        - name: run post installation
          ansible.builtin.expect:
            command: yunohost tools postinstall
            timeout: null
            responses:
              (?i)main domain: restic.test
              (?i)administration password: This is my password!
        - name: remove installation script
          file:
            path: "{{ installation_script_path }}"
            state: absent
      when: not _stat_etc_yunohost.stat.exists
