packaging_format = 2

id = "restic"
name = "Restic"
description.en = "Backup your server with Restic"
description.fr = "Sauvegardez votre serveur avec Restic"

version = "0.12.0~ynh9"

maintainers = ["Lionel Coupouchetty-Ramouchetty"]

[upstream]
license = "BSD-2-Clause"
website = "https://restic.net"
admindoc = "https://restic.readthedocs.io/en/latest/"
code = "https://github.com/restic/restic"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 11.2"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.server]
    ask.en = "Indicate the server where you want put your backups"
    ask.fr = "Indiquez le serveur où vous voulez faire vos sauvegardes"
    help.en = "IP address or resolvable hostname of your destination server"
    help.fr = "Adresse IP ou nom résolvable de votre serveur de destination"
    type = "string"
    example = "example.com"

    [install.port]
    ask.en = "sftp port of your server"
    ask.fr = "Le port sftp de votre serveur"
    help.en = "Listening port of your sftp or ssh server. The default value is 22"
    help.fr = "Le port d'écoute de votre serveur sftp ou ssh. La valeur par défaut est 22"
    type = "string"
    example = "22"
    default = "22"

    [install.backup_path]
    ask.en = "The directory where you want your backup repositories to be created in"
    ask.fr = "Le répertoire dans lequel les dépôts restic seront créés"
    help.en = "A complete or relative path to an existing directory on the remote server writable by the remote backup user. Defaults to the login directory"
    help.fr = "Un chemin complet ou relatif vers un répertoire existant sur le serveur distant et accessible en écriture au compte utilisé pour la sauvegarde. Répertoire d'accueil par défaut"
    type = "string"
    example = "./backups"
    default = "."

    [install.ssh_user]
    ask.en = "Indicate the ssh user to use to connect on this server"
    ask.fr = "Indiquez l'utilisateur ssh à utiliser pour se connecter au serveur"
    type = "string"
    example = "john"

    [install.passphrase]
    ask.en = "Indicate a strong passphrase, that you will keep preciously if you want to be able to use your backups"
    ask.fr = "Indiquez une phrase de passe forte que vous garderez précieusement si vous voulez être en mesure d'utiliser vos sauvegardes"
    type = "password"

    [install.conf]
    ask.en = "Would you like to backup your YunoHost configuration ?"
    ask.fr = "Souhaitez-vous effectuer des sauvegardes des configurations du système YunoHost ?"
    type = "boolean"
    default = true

    [install.data]
    ask.en = "Would you like to backup mails and user home directory ?"
    ask.fr = "Souhaitez-vous effectuer des sauvegardes des mails et des répertoire des utilisateurs ?"
    type = "boolean"
    default = true

    [install.apps]
    ask.en = "Which apps would you backup (list separated by comma or 'all') ?"
    ask.fr = "Souhaitez-vous effectuer des sauvegardes de vos applications ?"
    type = "string"
    default = "all"

    [install.allow_extra_space_use]
    ask.en = "Allow backup method to temporarily use more space?"
    ask.fr = "Permettre à la sauvegarde de consommer temporairement de l'espace supplémentaire?"
    help.en = "Some applications as Gitlab can't be backed up with the standard method and require extra space temporarily"
    help.fr = "Certaines applications comme Gitlab ne peuvent être sauvegardées avec la méthode standard et nécessitent d'utiliser plus d'espace disque temporairement"
    type = "boolean"
    default = true

    [install.on_calendar]
    ask.en = "Indicate the backup frequency (see systemd OnCalendar format)"
    ask.fr = "Indiquez la fréquence de la sauvegarde (voir le format OnCalendar de systemd)"
    type = "string"
    example = "Daily"
    default = "*-*-* 0:15:00"

    [install.check_on_calendar]
    ask.en = "Indicate the backup check frequency (see systemd OnCalendar format)"
    ask.fr = "Indiquez la fréquence de vérification de la sauvegarde (voir le format OnCalendar de systemd)"
    type = "string"
    example = "Tue *-*-* 00:15:00"
    default = "Sat *-*-8..31 3:15:00"

    [install.check_read_data_on_calendar]
    ask.en = "Indicate the complete backup check frequency (see systemd OnCalendar format)"
    ask.fr = "Indiquez la fréquence de vérification complète de la sauvegarde (voir le format OnCalendar de systemd)"
    type = "string"
    example = "Tue *-*-* 00:15:00"
    default = "Sat *-*-1..7 3:15:00"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
