#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "restic"
name = "Restic"
description.en = "Regularly create encrypted backups sent to another server using Restic"
description.fr = "Créez régulièrement des sauvegardes chiffrées envoyées sur un autre serveur avec Restic"

version = "0.18.0~ynh3"

maintainers = ["Gildas-GH"]

[upstream]
license = "BSD-2-Clause"
website = "https://restic.net"
admindoc = "https://restic.readthedocs.io/en/latest/"
code = "https://github.com/restic/restic"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.repository]
    ask.en = "In which location do you want to backup your files?"
    ask.fr = "Dans quel endroit souhaitez-vous sauvegarder vos fichiers ?"
    help.fr = "Spécifiez un serveur SFTP (`sftp://user@host:port//srv/restic-repo`) ou tout autre format de `--repo` supporté par Restic (voir https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html, you'll need to add environment variables manually)"
    help.en = "Specify a SFTP server (`sftp://user@host:port//srv/restic-repo`) or any other repository format supported by Restic (see https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html, vous devrez ajouter des variables d'environnement manuellement)"
    type = "string"
    example = "sftp://john@serverb.tld:22//backups"

    [install.passphrase]
    ask.en = "Provide a strong passphrase to encrypt your backups."
    ask.fr = "Indiquez une phrase de passe forte pour chiffrer vos sauvegardes."
    help.en = "Keep it safe! There will be **no way** to restore your backup if you lose it. Do not communicate it to the remote host server holder, or anyone else."
    help.fr = "Gardez-la précieusement ! Il sera impossible de restaurer vos sauvegardes sans celle-ci. Ne donnez pas cette clé à la personne qui gère le serveur distant - où à n'importe qui d'ailleurs."
    type = "password"

    [install.conf]
    ask.en = "Should Restic backup your YunoHost configuration?"
    ask.fr = "Restic doit-il sauvegarder la configuration système YunoHost ?"
    type = "boolean"
    default = true

    [install.data]
    ask.en = "Should Restic backup emails and user home directories?"
    ask.fr = "Restic doit-il sauvegarder les e-mails et les répertoires (home) des utilisateurs ?"
    type = "boolean"
    default = true

    [install.apps]
    ask.en = "Which apps should Restic backup ?"
    ask.fr = "Quelles applications doivent être sauvegardées par Restic ?"
    help.en = "App list separated by spaces. You can write 'all' to select all apps, including those installed after this Restic app. You can also select all apps except some by writing 'exclude:' followed by a space-separated list of apps."
    help.fr = "Liste d'applications séparées par des espaces. Vous pouvez écrire 'all' pour sélectionner toutes les apps, y compris celles installées après cette application Restic. Vous pouvez aussi sélectionner toutes les apps sauf certaines en écrivant 'exclude:' suivi d'une liste d'applications séparées par des espaces."
    type = "string"
    default = "all"

    [install.on_calendar]
    ask.en = "When and at which frequency should the backups be performed?"
    ask.fr = "Quand et à quelle fréquence les sauvegardes doivent-elles être effectuées ?"
    type = "string"
    help = "For example: `Monthly`, `Weekly`, `Daily` (=every day at midnight), `Hourly`, `Sat *-*-1..7 18:00:00` (=the first saturday of every month at 18:00), `4:00` (=every day at 4 AM), `5,17:00` (=every day at 5 AM and 5 PM). See the [systemd OnCalendar format for full syntax doc](https://wiki.archlinux.org/index.php/Systemd/Timers#Realtime_timer)"
    default = "Daily"

[resources]
    [resources.sources.main]
    amd64.url = "https://github.com/restic/restic/releases/download/v0.18.0/restic_0.18.0_linux_amd64.bz2"
    amd64.sha256 = "98f6dd8bf5b59058d04bfd8dab58e196cc2a680666ccee90275a3b722374438e"
    i386.url = "https://github.com/restic/restic/releases/download/v0.18.0/restic_0.18.0_linux_386.bz2"
    i386.sha256 = "c171b288885830863fa290a3bcdc4e50c0425758f3fff7ce7fef27741b0cf374"
    arm64.url = "https://github.com/restic/restic/releases/download/v0.18.0/restic_0.18.0_linux_arm64.bz2"
    arm64.sha256 = "ce18179c25dc5f2e33e3c233ba1e580f9de1a4566d2977e8d9600210363ec209"
    armhf.url = "https://github.com/restic/restic/releases/download/v0.18.0/restic_0.18.0_linux_arm.bz2"
    armhf.sha256 = "a202b58cb23c7b40e2562d9b0804492f77278bd0d0bf043f5e02951f89c83eb5"

    in_subdir = false
    rename = "restic.bz2"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
