#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.repository = "/tmp/test-restic"
    args.passphrase = "APassphrase"
    args.conf = 1
    args.data = 1
    args.apps = "restic"
    args.on_calendar = "Daily"

    [default.test_upgrade_from.526944051f68f4149e415be4e862ce3c69d69f18]
    name = "0.12.0~ynh9"

    [default.test_upgrade_from.075ce5d9b56f89649623e803e741b36ff5e481df]
    name = "last packaging v1"
